name: Docker Build and Push
permissions:
  contents: read
  pull-requests: read
  packages: write

on:
  push:
    branches: ["main"]
    paths:
      - "**.js"
      - "**.mjs"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"
      - "**.html"
      - "**.json"
      - "**/Dockerfile*"
      - "compose.yaml"
      - ".env.example"
      - ".github/workflows/docker.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.js"
      - "**.mjs"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"
      - "**.html"
      - "**.json"
      - "**/Dockerfile*"
      - "compose.yaml"
      - ".env.example"
      - ".github/workflows/docker.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: back
            context: .
            dockerfile: ./back/Dockerfile
            image: kntista-back
          - name: front
            context: .
            dockerfile: ./front/Dockerfile
            image: kntista-front

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env
        run: mv .env.example .env

      - name: Build and push (${{ matrix.name }})
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ matrix.image }}:latest
            ghcr.io/${{ env.OWNER_LC }}/${{ matrix.image }}:${{ github.sha }}

  compose:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env
        run: mv .env.example .env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3 # v2.5.0
        with:
          compose-file: "./compose.yaml"
          compose-flags: "--profile prod"
